# Generated by Django 6.1 on 2026-09-09 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
