# Generated by Django 6.1 on 2026-09-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
    ]
