# Generated by Django 6.1 on 2026-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_achievement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(),
        ),
    ]
