# Generated by Django 5.2.17 on 2026-09-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experience_starred_by_alter_achievement_achieved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
