# Generated by Django 5.2.17 on 2026-09-26 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_achievement_achieved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='starred_by',
        ),
        migrations.AddField(
            model_name='achievement',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_achivements', to=settings.AUTH_USER_MODEL),
        ),
    ]
